# Generated by Django 2.2.2 on 2019-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_style_subject_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.TextField(),
        ),
    ]
