# Generated by Django 2.2.2 on 2019-06-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_auto_20190619_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='ad')),
                ('des', models.TextField()),
                ('url', models.CharField(max_length=20)),
            ],
        ),
    ]
