# Generated by Django 2.2.2 on 2019-06-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='matter',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
