# Generated by Django 2.2.2 on 2019-06-20 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_auto_20190620_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
