# Generated by Django 2.2.2 on 2019-06-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0013_messageinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageInfo',
        ),
    ]
